spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.17.1.54:31082/accountservice_db}
    username: ${DB_USERNAME:clientservice_admin}
    password: ${DB_PASSWORD:clientservice_password}
  kafka:
    bootstrap-servers: ${KAFKA_URL:172.17.1.3:30092}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:eureka-service:8761/eureka}
account-closure-notification:
  topic: closure_account-notification
