spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/accountservice_db
    username: clientservice_admin
    password: clientservice_password
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    service-url:
      defaultZone: eureka-service:8761/eureka
account-closure-notification:
  topic: closure_account-notification
