spring:
  datasource:
    url: jdbc:postgresql://172.17.1.54:30082/accountservice_db
    username: clientservice_admin
    password: clientservice_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
