spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=PostgreSQL
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog-master.yml
eureka:
  client:
    enabled: false
services:
  infoservice:
    stub-enabled: false
    name: "infoservice"
    path: "/api/v1/infoservice"
    url: "localhost:8080"
  clientservice:
    name: "clientservice"
    path: "/api/v1/clientservice"
    url: "localhost:8080"
