spring:
  datasource:
    url: jdbc:postgresql://172.17.1.54:30082/accountservice_db
    username: clientservice_admin
    password: clientservice_password
  kafka:
    bootstrap-servers: 172.17.1.3:30092
eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka
account-closure-notification:
  topic: closure_account-notification
