spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.17.1.54:31082/accountservice_db}
    username: ${DB_USERNAME:clientservice_admin}
    password: ${DB_PASSWORD:clientservice_password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  kafka:
    bootstrap-servers: ${KAFKA_URL:172.17.1.3:30092}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:eureka-service:8761/eureka}
  instance:
    prefer-ip-address: true
account-closure-notification:
  topic: closure_account-notification
services:
  infoservice:
    stub-enabled: ${INFOSERVICE_STUB:true}
    name: "infoservice"
    path: "/api/v1/infoservice"
    url:
  clientservice:
    name: "clientservice"
    path: "/api/v1/clientservice"
    url:
