spring:
  data:
    redis:
      host: 172.17.1.3
      port: 30379
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
api-gateway:
  isStubEnabled: true
  isMasterTokenEnabled: true
