spring:
  datasource:
    url: jdbc:postgresql://172.17.1.54:30082/cardservice_db
    username: clientservice_admin
    password: clientservice_password
  kafka:
    bootstrap-servers: 172.17.1.3:30092
  account-closure-notification:
    topic: closure_account-notification
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
services:
  accountservice:
    stub-enabled: false
