spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/boomerang_db
    username: clientservice_admin
    password: clientservice_password
  kafka:
    bootstrap-servers: kafka:9092
topic:
  registration-notification: registration_customer-notification
  open-new-account: deposit_open-new-deposit
eureka:
  client:
    service-url:
      defaultZone: eureka-service:8761/eureka
