spring:
  datasource:
    url: jdbc:postgresql://172.17.1.54:30082/boomerang_db
    username: clientservice_admin
    password: clientservice_password
  kafka:
    bootstrap-servers: 172.17.1.3:30092
topic:
  registration-notification: registration_customer-notification
  open-new-account: deposit_open-new-deposit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
